services:
    minio:
        restart: always
        image: minio/minio
        container_name: mts_minio
        ports:
            - "${MINIO_PORT}:${MINIO_PORT}"
            - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
        command: server /data --console-address ":${MINIO_CONSOLE_PORT}" --address ":${MINIO_PORT}"
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - mts_minio_volume:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 60s

    mc:
        image: minio/mc
        container_name: mts_minio_client
        depends_on:
            minio:
                condition: service_completed_successfully
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        entrypoint: >
            /bin/sh -c "/usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} && /usr/bin/mc mb minio/mlflow; exit 0;"

    db:
        restart: always
        image: postgres:17.8
        container_name: mts_db
        expose:
            - "${DB_PORT}"
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - mts_db_volume:/var/lib/postgresql/data
        healthcheck:
            test: [
                "CMD-SHELL",
                "pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"
            ]
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 60s

    ofelia:
        restart: always
        image: mcuadros/ofelia:latest
        depends_on:
            - server
        container_name: mts_ofelia
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    server:
        restart: always
        build: .
        image: mts_server
        container_name: mts_server
        depends_on:
            mc:
                condition: service_started
            db:
                condition: service_healthy
        ports:
            - "${MLFLOW_SERVER_PORT}:5000"
        environment:
            - MLFLOW_ENABLE_WORKSPACES=1
            - MLFLOW_S3_ENDPOINT_URL=http://minio:${MINIO_PORT}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME} --default-artifact-root s3://mlflow/
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.datecron.schedule: "@every 6h"
            ofelia.job-exec.datecron.command: "mlflow gc --all-workspaces --backend-store-uri postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME} --tracking-uri=127.0.0.1:5000"

volumes:
    mts_db_volume:
    mts_minio_volume:
